const renderResumes = () => {
  const generatedListHtml = state.generatedResumes.length > 0 
    ? state.generatedResumes.map(cv => `
        <div class="flex justify-between items-center bg-white dark:bg-[#111] border-2 border-[#111] dark:border-gray-800 rounded-lg p-4 mb-3 shadow-[2px_2px_0px_0px_rgba(17,17,17,1)] dark:shadow-[2px_2px_0px_0px_rgba(255,255,255,0.05)] hover:shadow-none hover:translate-y-[2px] hover:translate-x-[2px] transition-all">
          <div>
            <div class="font-bold text-[14px] flex items-center gap-2 dark:text-white"><i data-lucide="file-check-2" class="w-4 h-4 text-green-600"></i> ${cv.company} Application</div>
            <div class="text-[11px] text-gray-500 dark:text-gray-400 mt-1">${cv.name} • Generated ${cv.date}</div>
          </div>
          <div class="flex items-center gap-2">
            <button class="p-1.5 border-2 border-transparent hover:border-[#111] dark:hover:border-gray-600 rounded-md transition-all text-blue-600 bg-blue-50 dark:bg-blue-900/20" title="Download"><i data-lucide="download" class="w-4 h-4"></i></button>
            <button class="p-1.5 border-2 border-transparent hover:border-[#111] dark:hover:border-gray-600 rounded-md transition-all text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-800" title="View"><i data-lucide="eye" class="w-4 h-4"></i></button>
          </div>
        </div>
      `).join('')
    : '<div class="text-center text-gray-500 font-bold p-6 border-2 border-dashed border-gray-300 dark:border-gray-800 rounded-lg">No tailored resumes generated yet. Go to an application to generate one.</div>';

  return `
    <div class="max-w-5xl mx-auto h-full flex flex-col transition-colors duration-300">
      <h2 class="text-[20px] mb-6 font-bold flex items-center gap-2 dark:text-white"><i data-lucide="file-text" class="w-5 h-5"></i> My Resumes</h2>
      
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6 flex-1 overflow-hidden pb-4">
        <div class="border-2 border-[#111] dark:border-gray-800 rounded-xl bg-white dark:bg-[#111] p-6 shadow-[4px_4px_0px_0px_rgba(17,17,17,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.05)] flex flex-col">
          <div class="flex justify-between items-center border-b-2 border-gray-100 dark:border-gray-800 pb-3 mb-4">
            <h3 class="font-bold text-[16px] dark:text-white">Global Base Resume</h3>
            <button onclick="document.getElementById('global-pdf-upload').click()" class="text-[11px] font-bold border-2 border-[#111] dark:border-gray-700 rounded-md px-3 py-1.5 bg-gray-50 dark:bg-gray-800 hover:bg-[#111] dark:hover:bg-white hover:text-white dark:hover:text-[#111] transition-colors flex items-center gap-1.5 dark:text-gray-300">
              <i data-lucide="upload" class="w-3 h-3"></i> Upload PDF
            </button>
            <input type="file" id="global-pdf-upload" class="hidden" accept=".pdf" onchange="handleGlobalUpload(event)">
          </div>
          <p class="text-[12px] text-gray-600 dark:text-gray-400 mb-4">Upload your standard PDF resume or paste the text below. The AI will extract and use this content to generate tailored resumes for specific job applications.</p>
          
          <div class="flex-1 flex flex-col min-h-[250px]">
            <label class="font-bold text-[12px] mb-1.5 text-gray-700 dark:text-gray-300">Extracted Resume Text</label>
            <textarea id="global-cv-input" class="w-full flex-1 border-2 border-[#111] dark:border-gray-700 rounded-md p-3 focus:outline-none focus:ring-2 focus:ring-[#111] dark:focus:ring-gray-500 text-[12px] resize-none bg-white dark:bg-[#0a0a0a] dark:text-gray-200">${state.globalCV}</textarea>
          </div>
          
          <button onclick="saveGlobalCV()" class="w-full border-2 border-[#111] dark:border-gray-700 rounded-md bg-[#111] dark:bg-white text-white dark:text-[#111] px-4 py-2.5 font-bold hover:bg-white dark:hover:bg-[#eee] hover:text-[#111] transition-colors mt-4 shadow-[2px_2px_0px_0px_rgba(17,17,17,1)] dark:shadow-[2px_2px_0px_0px_rgba(255,255,255,0.1)] hover:shadow-none hover:translate-y-[2px] hover:translate-x-[2px]">
            Save Base Resume
          </button>
        </div>

        <div class="border-2 border-[#111] dark:border-gray-800 rounded-xl bg-gray-50 dark:bg-[#0a0a0a] p-6 flex flex-col overflow-hidden">
          <h3 class="font-bold text-[16px] border-b-2 border-gray-200 dark:border-gray-800 pb-3 mb-4 dark:text-white">Tailored Resumes</h3>
          <p class="text-[12px] text-gray-600 dark:text-gray-400 mb-4">Resumes automatically generated by AI for specific job applications.</p>
          
          <div class="flex-1 overflow-y-auto pr-2 custom-scrollbar">
            ${generatedListHtml}
          </div>
        </div>
      </div>
    </div>
  `;
};
